import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { createServiceRoleClient } from "@/lib/supabase/service";
import { isMemoShareUnlockedFromCookie } from "@/lib/memoShareUnlock";
import { getSiteUrl } from "@/lib/site";
import SharedMemoPasswordForm from "./SharedMemoPasswordForm";
import SharedMemoView from "./SharedMemoView";

export const dynamic = "force-dynamic";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ token: string }>;
}): Promise<Metadata> {
  const { token } = await params;
  const base = getSiteUrl();
  const pageUrl = `${base}/shared/memo/${token}`;
  const service = createServiceRoleClient();
  const { data: link } = await service
    .from("memo_share_links")
    .select("scan_id, password_hash")
    .eq("token", token)
    .is("revoked_at", null)
    .maybeSingle();

  const defaultDesc =
    "Shared investment committee memo generated by CRE Signal Engine.";

  if (!link) {
    return {
      title: "Shared IC Memo",
      description: defaultDesc,
      openGraph: { title: "Shared IC Memo", description: defaultDesc, url: pageUrl },
      twitter: { card: "summary_large_image", title: "Shared IC Memo", description: defaultDesc },
    };
  }

  if ((link as { password_hash?: string | null }).password_hash) {
    return {
      title: "Shared IC Memo",
      description: defaultDesc,
      openGraph: { title: "Shared IC Memo", description: defaultDesc, url: pageUrl },
      twitter: { card: "summary_large_image", title: "Shared IC Memo", description: defaultDesc },
    };
  }

  const { data: scan } = await service
    .from("deal_scans")
    .select("deals!inner(name)")
    .eq("id", (link as { scan_id: string }).scan_id)
    .single();

  const dealName = (scan as { deals: { name: string } } | null)?.deals?.name ?? "IC Memo";
  const title = `${dealName} — IC Memo`;
  return {
    title,
    description: defaultDesc,
    openGraph: {
      title,
      description: defaultDesc,
      url: pageUrl,
      type: "article",
    },
    twitter: {
      card: "summary_large_image",
      title,
      description: defaultDesc,
    },
    alternates: {
      canonical: pageUrl,
    },
  };
}

export default async function SharedMemoPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;
  const service = createServiceRoleClient();

  const { data: link } = await service
    .from("memo_share_links")
    .select("id, scan_id, organization_id, view_count, expires_at, password_hash")
    .eq("token", token)
    .is("revoked_at", null)
    .maybeSingle();

  if (!link) notFound();

  const l = link as {
    id: string;
    scan_id: string;
    organization_id: string;
    view_count: number;
    expires_at: string | null;
    password_hash: string | null;
  };

  if (l.expires_at && new Date(l.expires_at) < new Date()) notFound();

  const unlocked = await isMemoShareUnlockedFromCookie(token, l.password_hash);
  if (l.password_hash && !unlocked) {
    return <SharedMemoPasswordForm token={token} />;
  }

  service
    .from("memo_share_links")
    .update({ view_count: l.view_count + 1 })
    .eq("id", l.id)
    .then(() => {});

  const { data: scan, error: scanError } = await service
    .from("deal_scans")
    .select("id, created_at, risk_index_score, risk_index_band, deal_id")
    .eq("id", l.scan_id)
    .maybeSingle();

  if (scanError) {
    console.error("[shared/memo page] deal_scans lookup error:", scanError);
    notFound();
  }
  if (!scan) notFound();

  const s = scan as {
    id: string;
    created_at: string;
    risk_index_score: number | null;
    risk_index_band: string | null;
    deal_id: string;
  };
  const { data: deal, error: dealError } = await service
    .from("deals")
    .select("name, asset_type, market")
    .eq("id", s.deal_id)
    .maybeSingle();

  if (dealError || !deal) {
    console.error("[shared/memo page] deals lookup error:", dealError);
    notFound();
  }
  const dealData = deal as { name: string; asset_type: string | null; market: string | null };

  const { data: narrativeRow } = await service
    .from("deal_scan_narratives")
    .select("content")
    .eq("deal_scan_id", l.scan_id)
    .maybeSingle();

  const narrativeContent = (narrativeRow as { content?: string } | null)?.content ?? null;

  const scanDateLabel = new Date(s.created_at).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <SharedMemoView
      dealName={dealData.name}
      assetType={dealData.asset_type}
      market={dealData.market}
      scanDateLabel={scanDateLabel}
      riskIndexScore={s.risk_index_score}
      riskIndexBand={s.risk_index_band}
      narrativeContent={narrativeContent}
    />
  );
}
