import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { createServiceRoleClient } from "@/lib/supabase/service";
import { renderMarkdown } from "@/lib/ui/renderMarkdown";

export const dynamic = "force-dynamic";

const BAND_COLORS: Record<string, string> = {
  Low: "#22c55e",
  Moderate: "#eab308",
  Elevated: "#f97316",
  High: "#ef4444",
};

export async function generateMetadata({
  params,
}: {
  params: Promise<{ token: string }>;
}): Promise<Metadata> {
  const { token } = await params;
  const service = createServiceRoleClient();
  const { data: link } = await service
    .from("memo_share_links")
    .select("scan_id")
    .eq("token", token)
    .is("revoked_at", null)
    .maybeSingle();

  if (!link) return { title: "Shared IC Memo | CRE Signal Engine" };

  const { data: scan } = await service
    .from("deal_scans")
    .select("deals!inner(name)")
    .eq("id", (link as { scan_id: string }).scan_id)
    .single();

  const dealName = (scan as { deals: { name: string } } | null)?.deals?.name ?? "IC Memo";
  return {
    title: `${dealName} — IC Memo | CRE Signal Engine`,
    description: "Shared investment committee memo generated by CRE Signal Engine.",
  };
}

export default async function SharedMemoPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;
  const service = createServiceRoleClient();

  // Fetch share link
  const { data: link } = await service
    .from("memo_share_links")
    .select("id, scan_id, organization_id, view_count, expires_at")
    .eq("token", token)
    .is("revoked_at", null)
    .maybeSingle();

  if (!link) notFound();

  const l = link as {
    id: string;
    scan_id: string;
    organization_id: string;
    view_count: number;
    expires_at: string | null;
  };

  if (l.expires_at && new Date(l.expires_at) < new Date()) notFound();

  // Increment view count (fire-and-forget)
  service
    .from("memo_share_links")
    .update({ view_count: l.view_count + 1 })
    .eq("id", l.id)
    .then(() => {});

  // Fetch public scan fields — NO financial extraction, NO raw_text
  const { data: scan } = await service
    .from("deal_scans")
    .select("id, created_at, risk_index_score, risk_index_band, deals!inner(name, asset_type, market)")
    .eq("id", l.scan_id)
    .single();

  if (!scan) notFound();

  const s = scan as {
    id: string;
    created_at: string;
    risk_index_score: number | null;
    risk_index_band: string | null;
    deals: { name: string; asset_type: string | null; market: string | null };
  };

  const { data: narrativeRow } = await service
    .from("deal_scan_narratives")
    .select("content")
    .eq("deal_scan_id", l.scan_id)
    .maybeSingle();

  const narrativeContent = (narrativeRow as { content?: string } | null)?.content ?? null;

  const bandColor = BAND_COLORS[s.risk_index_band ?? ""] ?? "#71717a";
  const scanDate = new Date(s.created_at).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <main style={{ maxWidth: 800, margin: "0 auto", padding: "40px 24px" }}>
      {/* Watermark / brand */}
      <div style={{ marginBottom: 24, display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <Link href="/" style={{ textDecoration: "none" }}>
          <span style={{ fontSize: 13, color: "#52525b", fontWeight: 600 }}>CRE Signal Engine</span>
        </Link>
        <span style={{ fontSize: 12, color: "#52525b" }}>Shared IC Memo</span>
      </div>

      {/* Deal header */}
      <div style={{ marginBottom: 24 }}>
        <h1 style={{ fontSize: 26, fontWeight: 700, color: "#fafafa", marginBottom: 4 }}>
          {s.deals.name}
        </h1>
        <p style={{ fontSize: 14, color: "#a1a1aa", margin: 0 }}>
          {[s.deals.asset_type, s.deals.market].filter(Boolean).join(" · ")} · Scanned {scanDate}
        </p>
      </div>

      {/* Risk score */}
      {s.risk_index_score != null && (
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 16,
            padding: "16px 20px",
            backgroundColor: "#18181b",
            border: `1px solid ${bandColor}40`,
            borderRadius: 10,
            marginBottom: 28,
          }}
        >
          <div style={{ fontSize: 42, fontWeight: 800, color: bandColor, lineHeight: 1, fontVariantNumeric: "tabular-nums" }}>
            {s.risk_index_score}
          </div>
          <div>
            <div style={{ fontSize: 18, fontWeight: 700, color: bandColor }}>{s.risk_index_band}</div>
            <div style={{ fontSize: 12, color: "#71717a", marginTop: 2 }}>CRE Signal Risk Index™</div>
          </div>
        </div>
      )}

      {/* Narrative */}
      {narrativeContent ? (
        <section style={{ marginBottom: 40 }}>
          <h2 style={{ fontSize: 16, fontWeight: 600, color: "#e4e4e7", marginBottom: 14 }}>
            IC Memorandum Narrative
          </h2>
          <div
            style={{
              padding: "20px 24px",
              border: "1px solid rgba(255,255,255,0.1)",
              borderRadius: 8,
              backgroundColor: "rgba(255,255,255,0.02)",
              fontSize: 14,
              color: "#e4e4e7",
            }}
          >
            {renderMarkdown(narrativeContent)}
          </div>
        </section>
      ) : (
        <div
          style={{
            padding: "20px 24px",
            border: "1px solid rgba(255,255,255,0.08)",
            borderRadius: 8,
            marginBottom: 40,
          }}
        >
          <p style={{ color: "#71717a", fontSize: 14, margin: 0 }}>
            IC memo narrative has not been generated for this scan.
          </p>
        </div>
      )}

      {/* Footer */}
      <div
        style={{
          borderTop: "1px solid rgba(255,255,255,0.08)",
          paddingTop: 24,
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          flexWrap: "wrap",
          gap: 12,
        }}
      >
        <p style={{ fontSize: 13, color: "#52525b", margin: 0 }}>
          Powered by{" "}
          <Link href="/" style={{ color: "#71717a", textDecoration: "none" }}>
            CRE Signal Engine
          </Link>{" "}
          · Institutional risk governance for CRE deals
        </p>
        <Link
          href="/login"
          style={{
            fontSize: 13,
            color: "#3b82f6",
            textDecoration: "none",
            fontWeight: 600,
          }}
        >
          Analyze your own deals →
        </Link>
      </div>

      {/* Disclaimer */}
      <p style={{ fontSize: 11, color: "#3f3f46", marginTop: 16, lineHeight: 1.5 }}>
        CRE Signal Engine is an underwriting support tool. This memo does not constitute investment advice.
        Financial assumptions are not displayed in shared memos.
      </p>
    </main>
  );
}
