import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { createServiceRoleClient } from "@/lib/supabase/service";
import { renderMarkdown } from "@/lib/ui/renderMarkdown";

export const dynamic = "force-dynamic";

const BAND_COLORS: Record<string, string> = {
  Low: "#22c55e",
  Moderate: "#eab308",
  Elevated: "#f97316",
  High: "#ef4444",
};

export async function generateMetadata({
  params,
}: {
  params: Promise<{ token: string }>;
}): Promise<Metadata> {
  const { token } = await params;
  const service = createServiceRoleClient();
  const { data: link } = await service
    .from("memo_share_links")
    .select("scan_id")
    .eq("token", token)
    .is("revoked_at", null)
    .maybeSingle();

  if (!link) return { title: "Shared IC Memo | CRE Signal Engine" };

  const { data: scan } = await service
    .from("deal_scans")
    .select("deals!inner(name)")
    .eq("id", (link as { scan_id: string }).scan_id)
    .single();

  const dealName = (scan as { deals: { name: string } } | null)?.deals?.name ?? "IC Memo";
  return {
    title: `${dealName} — IC Memo | CRE Signal Engine`,
    description: "Shared investment committee memo generated by CRE Signal Engine.",
  };
}

export default async function SharedMemoPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;
  const service = createServiceRoleClient();

  console.log("[shared/memo page] token:", token);

  // Fetch share link: memo_share_links by token, revoked_at IS NULL
  const { data: link } = await service
    .from("memo_share_links")
    .select("id, scan_id, organization_id, view_count, expires_at")
    .eq("token", token)
    .is("revoked_at", null)
    .maybeSingle();

  console.log("[shared/memo page] memo_share_links result:", link ?? null);

  if (!link) notFound();

  const l = link as {
    id: string;
    scan_id: string;
    organization_id: string;
    view_count: number;
    expires_at: string | null;
  };

  if (l.expires_at && new Date(l.expires_at) < new Date()) notFound();

  // Increment view count (fire-and-forget)
  service
    .from("memo_share_links")
    .update({ view_count: l.view_count + 1 })
    .eq("id", l.id)
    .then(() => {});

  // Fetch scan (two-step: deal_scans then deals — avoid embed/join failure)
  const { data: scan, error: scanError } = await service
    .from("deal_scans")
    .select("id, created_at, risk_index_score, risk_index_band, deal_id")
    .eq("id", l.scan_id)
    .maybeSingle();

  if (scanError) {
    console.error("[shared/memo page] deal_scans lookup error:", scanError);
    notFound();
  }
  if (!scan) {
    console.log("[shared/memo page] deal_scans: no row for scan_id", l.scan_id);
    notFound();
  }

  const s = scan as { id: string; created_at: string; risk_index_score: number | null; risk_index_band: string | null; deal_id: string };
  const { data: deal, error: dealError } = await service
    .from("deals")
    .select("name, asset_type, market")
    .eq("id", s.deal_id)
    .maybeSingle();

  if (dealError || !deal) {
    console.error("[shared/memo page] deals lookup error:", dealError);
    notFound();
  }
  const dealData = deal as { name: string; asset_type: string | null; market: string | null };

  const { data: narrativeRow } = await service
    .from("deal_scan_narratives")
    .select("content")
    .eq("deal_scan_id", l.scan_id)
    .maybeSingle();

  const narrativeContent = (narrativeRow as { content?: string } | null)?.content ?? null;
  console.log("[shared/memo page] narrative:", narrativeContent == null ? "null" : `${(narrativeContent as string).length} chars`);

  const bandColor = BAND_COLORS[s.risk_index_band ?? ""] ?? "#71717a";
  const scanDate = new Date(s.created_at).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <main className="max-w-[800px] mx-auto py-10 px-6 bg-white dark:bg-black text-gray-900 dark:text-white">
      {/* Watermark / brand */}
      <div className="mb-6 flex justify-between items-center">
        <Link href="/" className="no-underline">
          <span className="text-[13px] text-gray-500 dark:text-zinc-500 font-semibold">CRE Signal Engine</span>
        </Link>
        <span className="text-xs text-gray-500 dark:text-zinc-500">Shared IC Memo</span>
      </div>

      {/* Deal header */}
      <div className="mb-6">
        <h1 className="text-[26px] font-bold text-gray-900 dark:text-white mb-1">
          {dealData?.name}
        </h1>
        <p className="text-sm text-gray-500 dark:text-gray-400 m-0">
          {[dealData?.asset_type, dealData?.market].filter(Boolean).join(" · ")} · Scanned {scanDate}
        </p>
      </div>

      {/* Risk score */}
      {s.risk_index_score != null && (
        <div
          className="flex items-center gap-4 py-4 px-5 rounded-lg mb-7 bg-gray-100 dark:bg-zinc-900 border"
          style={{ borderColor: `${bandColor}40` }}
        >
          <div className="text-[42px] font-extrabold tabular-nums leading-none" style={{ color: bandColor }}>
            {s.risk_index_score}
          </div>
          <div>
            <div className="text-lg font-bold" style={{ color: bandColor }}>{s.risk_index_band}</div>
            <div className="text-xs text-gray-500 dark:text-zinc-400 mt-0.5">CRE Signal Risk Index™</div>
          </div>
        </div>
      )}

      {/* Narrative */}
      {narrativeContent ? (
        <section className="mb-10">
          <h2 className="text-base font-semibold text-gray-900 dark:text-zinc-200 mb-3.5">
            IC Memorandum Narrative
          </h2>
          <div className="py-5 px-6 border border-gray-200 dark:border-white/10 rounded-lg bg-gray-50 dark:bg-white/[0.02] text-sm text-gray-900 dark:text-zinc-200">
            {renderMarkdown(narrativeContent)}
          </div>
        </section>
      ) : (
        <div className="py-5 px-6 border border-gray-200 dark:border-white/8 rounded-lg mb-10">
          <p className="text-gray-500 dark:text-zinc-400 text-sm m-0">
            IC memo narrative has not been generated for this scan.
          </p>
        </div>
      )}

      {/* Footer */}
      <div className="border-t border-gray-200 dark:border-white/8 pt-6 flex justify-between items-center flex-wrap gap-3">
        <p className="text-[13px] text-gray-500 dark:text-zinc-500 m-0">
          Powered by{" "}
          <Link href="/" className="text-gray-500 dark:text-zinc-400 no-underline">
            CRE Signal Engine
          </Link>{" "}
          · Institutional risk governance for CRE deals
        </p>
        <Link
          href="/login"
          className="text-[13px] text-[#3b82f6] no-underline font-semibold"
        >
          Analyze your own deals →
        </Link>
      </div>

      {/* Disclaimer */}
      <p className="text-[11px] text-gray-500 dark:text-zinc-500 mt-4 leading-relaxed">
        CRE Signal Engine is an underwriting support tool. This memo does not constitute investment advice.
        Financial assumptions are not displayed in shared memos.
      </p>
    </main>
  );
}
