import type { Metadata } from "next";
import Link from "next/link";
import { renderMarkdown } from "@/lib/ui/renderMarkdown";

export const metadata: Metadata = {
  title: "Sample IC Memo | CRE Signal Engine",
  description:
    "See what a governed underwriting process looks like — no login required.",
};

const BAND_COLORS: Record<string, string> = {
  Low: "#22c55e",
  Moderate: "#eab308",
  Elevated: "#f97316",
  High: "#ef4444",
};

const SAMPLE_SCORE = 39;
const SAMPLE_BAND = "Moderate";

const SAMPLE_ASSUMPTIONS = [
  { key: "Asset Type", value: "Office" },
  { key: "Market", value: "Austin, TX" },
  { key: "Purchase Price", value: "$14,200,000" },
  { key: "Cap Rate In", value: "6.1%" },
  { key: "LTV", value: "68%" },
  { key: "NOI Year 1", value: "$866,200" },
  { key: "Hold Period", value: "7 years" },
  { key: "Exit Cap Rate", value: "6.6%" },
  { key: "Debt Rate", value: "6.50%" },
  { key: "Vacancy", value: "7%" },
];

const SAMPLE_RISKS = [
  {
    type: "ExitCapCompressionRisk",
    severity: "Medium",
    description:
      "Exit cap of 6.6% against entry of 6.1% represents 50bps compression. Office absorption in Austin softening; cap rate spread to treasuries compressed.",
  },
  {
    type: "RefinancingRisk",
    severity: "Low",
    description:
      "DSCR estimated at 1.31x. Adequate cushion at current debt rate but sensitive to rate increases at refinance.",
  },
  {
    type: "MarketLiquidityRisk",
    severity: "Low",
    description:
      "Austin office market remains liquid with institutional buyer depth, though transaction velocity has slowed in the 50,000–100,000 SF segment.",
  },
  {
    type: "SupplyRisk",
    severity: "Medium",
    description:
      "13.2M SF of office under construction in the Austin MSA. New deliveries concentrated in Southeast submarket, proximate to subject.",
  },
];

const SAMPLE_NARRATIVE = `# IC Memorandum — Riverside Commerce Center

## Executive Summary

Riverside Commerce Center is a 98,400 SF Class B office asset located in Southeast Austin, TX. The CRE Signal Risk Index™ scores this acquisition at **39 — Moderate**, reflecting adequate structural underwriting offset by supply-side pressure and mild exit cap compression risk.

## Deal Assumptions and Structure

The acquisition is structured at a 6.1% going-in cap rate on a $14.2M purchase price, implying an NOI of $866,200 in Year 1. LTV of 68% at a 6.50% debt rate provides a 1.31x DSCR — above the 1.25x institutional floor but without significant margin. The 7-year hold and 6.6% exit cap represent a conservative 50bps compression assumption.

## Primary Risk Factors

**Exit Cap Compression (Medium Confidence):** The 50bps spread between entry and exit cap rates is the primary source of score elevation. Office cap rate spreads to 10-year treasuries remain compressed historically, and the Austin market has seen softening buyer demand in the sub-100K SF segment over the trailing two quarters.

**Supply Exposure (Medium Confidence):** 13.2M SF of office space is under construction across the Austin MSA, with meaningful deliveries in the Southeast submarket through 2026. This supply concentration could pressure rents and occupancy assumptions during the hold.

## Stabilizing Factors

Conservative LTV (68%) provides structural cushion. Class B office in Austin maintains strong tenant demand from professional services and regional headquarters. In-place tenancy is diversified across three tenants with staggered lease expirations.

## Macro Signal Context

Two active CRE Signal macro alerts are cross-referenced to this deal: (1) rising office vacancy in Sun Belt secondary markets, and (2) softening rent growth projections for office in high-supply corridors. These signals are reflected in the score.

## Recommendation Framework

**Score: 39 — Moderate.** Standard IC review cadence is appropriate. Stress test recommended: (1) exit cap at 7.0% (100bps compression) to validate residual value floor; (2) Year 3 occupancy at 85% to model supply absorption impact on NOI. No structural deficiencies identified that would preclude approval under current assumptions.

---
*Generated by CRE Signal Engine v2.0 (Institutional Stable). Deterministic scoring — identical inputs produce identical outputs.*`;

export default function SampleReportPage() {
  const bandColor = BAND_COLORS[SAMPLE_BAND] ?? "#eab308";

  return (
    <main className="max-w-[800px] mx-auto py-10 px-6 bg-white dark:bg-black text-gray-900 dark:text-white">
      {/* Header */}
      <div className="mb-8 text-center">
        <p className="text-[13px] text-gray-500 dark:text-zinc-400 mb-2 uppercase tracking-wider">
          CRE Signal Engine
        </p>
        <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-3">
          See CRE Signal Engine in Action
        </h1>
        <p className="text-gray-500 dark:text-gray-400 text-base leading-relaxed max-w-[560px] mx-auto">
          See what a governed underwriting process looks like — no login required.
        </p>
      </div>

      {/* Risk Score Badge */}
      <div
        className="flex items-center gap-4 py-4 px-5 rounded-lg mb-6 bg-gray-100 dark:bg-zinc-900 border"
        style={{ borderColor: `${bandColor}40` }}
      >
        <div className="text-[42px] font-extrabold tabular-nums leading-none" style={{ color: bandColor }}>
          {SAMPLE_SCORE}
        </div>
        <div>
          <div className="text-lg font-bold" style={{ color: bandColor }}>{SAMPLE_BAND}</div>
          <div className="text-xs text-gray-500 dark:text-zinc-400 mt-0.5">CRE Signal Risk Index™</div>
        </div>
        <div className="ml-auto text-right">
          <div className="text-sm font-semibold text-gray-900 dark:text-zinc-200">
            Riverside Commerce Center
          </div>
          <div className="text-[13px] text-gray-500 dark:text-gray-400">Austin, TX · Office</div>
        </div>
      </div>

      {/* Key Assumptions */}
      <section className="mb-7">
        <h2 className="text-base font-semibold text-gray-900 dark:text-zinc-200 mb-3">
          Key Assumptions
        </h2>
        <div className="border border-gray-200 dark:border-white/10 rounded-lg overflow-hidden">
          <table className="w-full border-collapse text-sm">
            <tbody>
              {SAMPLE_ASSUMPTIONS.map((a, i) => (
                <tr
                  key={a.key}
                  className={i < SAMPLE_ASSUMPTIONS.length - 1 ? "border-b border-gray-200 dark:border-white/7" : ""}
                >
                  <td className="py-2 px-3.5 text-gray-500 dark:text-gray-400 w-[45%]">{a.key}</td>
                  <td className="py-2 px-3.5 text-gray-900 dark:text-zinc-200 font-medium">{a.value}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      {/* Primary Risks */}
      <section className="mb-7">
        <h2 className="text-base font-semibold text-gray-900 dark:text-zinc-200 mb-3">
          Primary Risks
        </h2>
        <div className="flex flex-col gap-2.5">
          {SAMPLE_RISKS.map((r) => (
            <div
              key={r.type}
              className="py-3 px-4 rounded-lg bg-gray-100 dark:bg-zinc-900 border border-gray-200 dark:border-white/8"
            >
              <div className="flex gap-2.5 items-center mb-1.5">
                <span className="text-xs text-gray-500 dark:text-zinc-400">{r.type}</span>
                <span
                  className="text-[11px] font-semibold py-0.5 px-1.5 rounded"
                  style={{
                    color: r.severity === "High" ? "#ef4444" : r.severity === "Medium" ? "#eab308" : "#22c55e",
                    backgroundColor: r.severity === "High" ? "rgba(239,68,68,0.15)" : r.severity === "Medium" ? "rgba(234,179,8,0.15)" : "rgba(34,197,94,0.15)",
                  }}
                >
                  {r.severity}
                </span>
              </div>
              <p className="m-0 text-[13px] text-gray-500 dark:text-gray-400 leading-snug">{r.description}</p>
            </div>
          ))}
        </div>
      </section>

      {/* IC Narrative */}
      <section className="mb-8">
        <h2 className="text-base font-semibold text-gray-900 dark:text-zinc-200 mb-3">
          IC Memorandum Narrative
        </h2>
        <div className="py-5 px-6 border border-gray-200 dark:border-white/10 rounded-lg bg-gray-50 dark:bg-white/[0.02] text-sm text-gray-900 dark:text-zinc-200">
          {renderMarkdown(SAMPLE_NARRATIVE)}
        </div>
      </section>

      {/* CTAs */}
      <div className="flex gap-4 flex-wrap mb-10 py-5 px-6 rounded-lg bg-gray-100 dark:bg-zinc-900 border border-gray-200 dark:border-white/10">
        <a
          href="/sample-report.pdf"
          download
          className="inline-flex items-center gap-2 py-3 px-6 bg-gray-200 dark:bg-white/10 text-gray-900 dark:text-zinc-200 border border-gray-300 dark:border-white/20 rounded-lg font-semibold text-sm no-underline"
        >
          Download Sample PDF
        </a>
        <Link
          href="/login"
          className="inline-flex items-center gap-2 py-3 px-6 bg-[#3b82f6] text-white border-0 rounded-lg font-semibold text-sm no-underline"
        >
          Analyze Your Own Deal →
        </Link>
      </div>

      {/* Footer */}
      <div className="text-center border-t border-gray-200 dark:border-white/8 pt-6">
        <p className="text-gray-500 dark:text-zinc-500 text-[13px]">
          Generated by{" "}
          <Link href="/" className="text-gray-500 dark:text-zinc-400 no-underline">
            CRE Signal Engine
          </Link>{" "}
          · {new Date().getFullYear()} · Not investment advice
        </p>
      </div>
    </main>
  );
}
