import type { Metadata } from "next";
import Link from "next/link";
import { renderMarkdown } from "@/lib/ui/renderMarkdown";

export const metadata: Metadata = {
  title: "Sample IC Memo | CRE Signal Engine",
  description:
    "A live example of an AI-generated Investment Committee memo with institutional risk scoring — no login required.",
};

const BAND_COLORS: Record<string, string> = {
  Low: "#22c55e",
  Moderate: "#eab308",
  Elevated: "#f97316",
  High: "#ef4444",
};

const SAMPLE_SCORE = 39;
const SAMPLE_BAND = "Moderate";

const SAMPLE_ASSUMPTIONS = [
  { key: "Asset Type", value: "Industrial / Flex" },
  { key: "Market", value: "Austin, TX" },
  { key: "Purchase Price", value: "$14,200,000" },
  { key: "Cap Rate In", value: "6.1%" },
  { key: "LTV", value: "68%" },
  { key: "NOI Year 1", value: "$866,200" },
  { key: "Hold Period", value: "7 years" },
  { key: "Exit Cap Rate", value: "6.6%" },
  { key: "Debt Rate", value: "6.50%" },
  { key: "Vacancy", value: "7%" },
];

const SAMPLE_RISKS = [
  {
    type: "ExitCapCompressionRisk",
    severity: "Medium",
    description:
      "Exit cap of 6.6% against entry of 6.1% represents 50bps compression. Industrial absorption in Austin softening; cap rate spread to treasuries compressed.",
  },
  {
    type: "RefinancingRisk",
    severity: "Low",
    description:
      "DSCR estimated at 1.31x. Adequate cushion at current debt rate but sensitive to rate increases at refinance.",
  },
  {
    type: "MarketLiquidityRisk",
    severity: "Low",
    description:
      "Austin industrial market remains liquid with institutional buyer depth, though transaction velocity has slowed in the 50,000–100,000 SF segment.",
  },
  {
    type: "SupplyRisk",
    severity: "Medium",
    description:
      "13.2M SF of industrial under construction in the Austin MSA. New deliveries concentrated in Southeast submarket, proximate to subject.",
  },
];

const SAMPLE_NARRATIVE = `# IC Memorandum — Riverside Commerce Center

## Executive Summary

Riverside Commerce Center is a 98,400 SF Class B industrial/flex asset located in Southeast Austin, TX. The CRE Signal Risk Index™ scores this acquisition at **39 — Moderate**, reflecting adequate structural underwriting offset by supply-side pressure and mild exit cap compression risk.

## Deal Assumptions and Structure

The acquisition is structured at a 6.1% going-in cap rate on a $14.2M purchase price, implying an NOI of $866,200 in Year 1. LTV of 68% at a 6.50% debt rate provides a 1.31x DSCR — above the 1.25x institutional floor but without significant margin. The 7-year hold and 6.6% exit cap represent a conservative 50bps compression assumption.

## Primary Risk Factors

**Exit Cap Compression (Medium Confidence):** The 50bps spread between entry and exit cap rates is the primary source of score elevation. Industrial cap rate spreads to 10-year treasuries remain compressed historically, and the Austin market has seen softening buyer demand in the sub-100K SF segment over the trailing two quarters.

**Supply Exposure (Medium Confidence):** 13.2M SF of industrial space is under construction across the Austin MSA, with meaningful deliveries in the Southeast submarket through 2026. This supply concentration could pressure rents and occupancy assumptions during the hold.

## Stabilizing Factors

Conservative LTV (68%) provides structural cushion. Class B industrial in Austin maintains strong tenant demand from last-mile logistics and light manufacturing sectors. In-place tenancy is diversified across three tenants with staggered lease expirations.

## Macro Signal Context

Two active CRE Signal macro alerts are cross-referenced to this deal: (1) rising industrial vacancy in Sun Belt secondary markets, and (2) softening rent growth projections for flex/industrial in high-supply corridors. These signals are reflected in the score.

## Recommendation Framework

**Score: 39 — Moderate.** Standard IC review cadence is appropriate. Stress test recommended: (1) exit cap at 7.0% (100bps compression) to validate residual value floor; (2) Year 3 occupancy at 85% to model supply absorption impact on NOI. No structural deficiencies identified that would preclude approval under current assumptions.

---
*Generated by CRE Signal Engine v2.0 (Institutional Stable). Deterministic scoring — identical inputs produce identical outputs.*`;

export default function SampleReportPage() {
  const bandColor = BAND_COLORS[SAMPLE_BAND] ?? "#eab308";

  return (
    <main style={{ maxWidth: 800, margin: "0 auto", padding: "40px 24px" }}>
      {/* Header */}
      <div style={{ marginBottom: 32, textAlign: "center" }}>
        <p style={{ fontSize: 13, color: "#71717a", marginBottom: 8, textTransform: "uppercase", letterSpacing: "0.05em" }}>
          CRE Signal Engine
        </p>
        <h1 style={{ fontSize: 32, fontWeight: 700, color: "#fafafa", marginBottom: 12 }}>
          See CRE Signal Engine in Action
        </h1>
        <p style={{ color: "#a1a1aa", fontSize: 16, lineHeight: 1.6, maxWidth: 560, margin: "0 auto" }}>
          A live example of an AI-generated IC Memo with institutional risk scoring — no login required.
        </p>
      </div>

      {/* Risk Score Badge */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: 16,
          padding: "16px 20px",
          backgroundColor: "#18181b",
          border: `1px solid ${bandColor}40`,
          borderRadius: 10,
          marginBottom: 24,
        }}
      >
        <div
          style={{
            fontSize: 42,
            fontWeight: 800,
            color: bandColor,
            lineHeight: 1,
            fontVariantNumeric: "tabular-nums",
          }}
        >
          {SAMPLE_SCORE}
        </div>
        <div>
          <div style={{ fontSize: 18, fontWeight: 700, color: bandColor }}>{SAMPLE_BAND}</div>
          <div style={{ fontSize: 12, color: "#71717a", marginTop: 2 }}>CRE Signal Risk Index™</div>
        </div>
        <div style={{ marginLeft: "auto", textAlign: "right" }}>
          <div style={{ fontSize: 14, fontWeight: 600, color: "#e4e4e7" }}>
            Riverside Commerce Center
          </div>
          <div style={{ fontSize: 13, color: "#a1a1aa" }}>Austin, TX · Industrial/Flex</div>
        </div>
      </div>

      {/* Key Assumptions */}
      <section style={{ marginBottom: 28 }}>
        <h2 style={{ fontSize: 16, fontWeight: 600, color: "#e4e4e7", marginBottom: 12 }}>
          Key Assumptions
        </h2>
        <div
          style={{
            border: "1px solid rgba(255,255,255,0.1)",
            borderRadius: 8,
            overflow: "hidden",
          }}
        >
          <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 14 }}>
            <tbody>
              {SAMPLE_ASSUMPTIONS.map((a, i) => (
                <tr
                  key={a.key}
                  style={{
                    borderBottom: i < SAMPLE_ASSUMPTIONS.length - 1 ? "1px solid rgba(255,255,255,0.07)" : undefined,
                  }}
                >
                  <td style={{ padding: "8px 14px", color: "#a1a1aa", width: "45%" }}>{a.key}</td>
                  <td style={{ padding: "8px 14px", color: "#e4e4e7", fontWeight: 500 }}>{a.value}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      {/* Primary Risks */}
      <section style={{ marginBottom: 28 }}>
        <h2 style={{ fontSize: 16, fontWeight: 600, color: "#e4e4e7", marginBottom: 12 }}>
          Primary Risks
        </h2>
        <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
          {SAMPLE_RISKS.map((r) => (
            <div
              key={r.type}
              style={{
                padding: "12px 16px",
                backgroundColor: "#18181b",
                border: "1px solid rgba(255,255,255,0.08)",
                borderRadius: 8,
              }}
            >
              <div style={{ display: "flex", gap: 10, alignItems: "center", marginBottom: 6 }}>
                <span style={{ fontSize: 12, color: "#71717a" }}>{r.type}</span>
                <span
                  style={{
                    fontSize: 11,
                    fontWeight: 600,
                    color: r.severity === "High" ? "#ef4444" : r.severity === "Medium" ? "#eab308" : "#22c55e",
                    backgroundColor: r.severity === "High" ? "rgba(239,68,68,0.15)" : r.severity === "Medium" ? "rgba(234,179,8,0.15)" : "rgba(34,197,94,0.15)",
                    padding: "1px 6px",
                    borderRadius: 4,
                  }}
                >
                  {r.severity}
                </span>
              </div>
              <p style={{ margin: 0, fontSize: 13, color: "#a1a1aa", lineHeight: 1.55 }}>{r.description}</p>
            </div>
          ))}
        </div>
      </section>

      {/* IC Narrative */}
      <section style={{ marginBottom: 32 }}>
        <h2 style={{ fontSize: 16, fontWeight: 600, color: "#e4e4e7", marginBottom: 12 }}>
          IC Memorandum Narrative
        </h2>
        <div
          style={{
            padding: "20px 24px",
            border: "1px solid rgba(255,255,255,0.1)",
            borderRadius: 8,
            backgroundColor: "rgba(255,255,255,0.02)",
            fontSize: 14,
            color: "#e4e4e7",
          }}
        >
          {renderMarkdown(SAMPLE_NARRATIVE)}
        </div>
      </section>

      {/* CTAs */}
      <div
        style={{
          display: "flex",
          gap: 16,
          flexWrap: "wrap",
          marginBottom: 40,
          padding: "20px 24px",
          backgroundColor: "#18181b",
          border: "1px solid rgba(255,255,255,0.1)",
          borderRadius: 10,
        }}
      >
        <a
          href="/sample-report.pdf"
          download
          style={{
            display: "inline-flex",
            alignItems: "center",
            gap: 8,
            padding: "12px 24px",
            backgroundColor: "rgba(255,255,255,0.1)",
            color: "#e4e4e7",
            border: "1px solid rgba(255,255,255,0.2)",
            borderRadius: 8,
            fontWeight: 600,
            fontSize: 14,
            textDecoration: "none",
          }}
        >
          Download Sample PDF
        </a>
        <Link
          href="/login"
          style={{
            display: "inline-flex",
            alignItems: "center",
            gap: 8,
            padding: "12px 24px",
            backgroundColor: "#3b82f6",
            color: "#fff",
            border: "none",
            borderRadius: 8,
            fontWeight: 600,
            fontSize: 14,
            textDecoration: "none",
          }}
        >
          Analyze Your Own Deal →
        </Link>
      </div>

      {/* Footer */}
      <div style={{ textAlign: "center", borderTop: "1px solid rgba(255,255,255,0.08)", paddingTop: 24 }}>
        <p style={{ color: "#52525b", fontSize: 13 }}>
          Generated by{" "}
          <Link href="/" style={{ color: "#71717a", textDecoration: "none" }}>
            CRE Signal Engine
          </Link>{" "}
          · {new Date().getFullYear()} · Not investment advice
        </p>
      </div>
    </main>
  );
}
