/**
 * Generate the static sample IC memo PDF for /sample-report.
 * Run with: npm run generate:sample-pdf
 *
 * Output: public/sample-report.pdf
 */
import { buildIcMemoPdf } from "../lib/export/buildIcMemoPdf";
import { writeFileSync } from "fs";
import { join } from "path";

const SAMPLE_NARRATIVE = `# IC Memorandum — Riverside Commerce Center

## Executive Summary

Riverside Commerce Center is a 98,400 SF Class B industrial/flex asset located in Southeast Austin, TX. The CRE Signal Risk Index(TM) scores this acquisition at 39 - Moderate, reflecting adequate structural underwriting offset by supply-side pressure and mild exit cap compression risk.

## Deal Assumptions and Structure

The acquisition is structured at a 6.1% going-in cap rate on a $14.2M purchase price, implying an NOI of $866,200 in Year 1. LTV of 68% at a 6.50% debt rate provides a 1.31x DSCR - above the 1.25x institutional floor but without significant margin. The 7-year hold and 6.6% exit cap represent a conservative 50bps compression assumption.

## Primary Risk Factors

Exit Cap Compression (Medium Confidence): The 50bps spread between entry and exit cap rates is the primary source of score elevation. Industrial cap rate spreads to 10-year treasuries remain compressed historically, and the Austin market has seen softening buyer demand in the sub-100K SF segment over the trailing two quarters.

Supply Exposure (Medium Confidence): 13.2M SF of industrial space is under construction across the Austin MSA, with meaningful deliveries in the Southeast submarket through 2026. This supply concentration could pressure rents and occupancy assumptions during the hold.

## Stabilizing Factors

Conservative LTV (68%) provides structural cushion. Class B industrial in Austin maintains strong tenant demand from last-mile logistics and light manufacturing sectors. In-place tenancy is diversified across three tenants with staggered lease expirations.

## Macro Signal Context

Two active CRE Signal macro alerts are cross-referenced to this deal: (1) rising industrial vacancy in Sun Belt secondary markets, and (2) softening rent growth projections for flex/industrial in high-supply corridors. These signals are reflected in the score.

## Recommendation Framework

Score: 39 - Moderate. Standard IC review cadence is appropriate. Stress test recommended: (1) exit cap at 7.0% (100bps compression) to validate residual value floor; (2) Year 3 occupancy at 85% to model supply absorption impact on NOI. No structural deficiencies identified that would preclude approval under current assumptions.

Generated by CRE Signal Engine v2.0 (Institutional Stable). Deterministic scoring - identical inputs produce identical outputs.`;

async function main() {
  console.log("Generating sample-report.pdf...");
  const bytes = await buildIcMemoPdf({
    narrative: SAMPLE_NARRATIVE,
    dealName: "Riverside Commerce Center",
    scanCreatedAt: new Date().toISOString(),
    scanId: "sample",
    riskIndexScore: 39,
    riskIndexBand: "Moderate",
  });

  const outPath = join(process.cwd(), "public", "sample-report.pdf");
  writeFileSync(outPath, bytes);
  console.log(`Written: ${outPath} (${bytes.length} bytes)`);
}

main().catch((err) => {
  console.error("Failed to generate sample PDF:", err);
  process.exit(1);
});
