/**
 * Generate the static sample IC memo PDF for /sample-report.
 * Run with: npm run generate:sample-pdf  OR  npx tsx scripts/generateSamplePdf.ts
 *
 * Output: public/sample-report.pdf
 */
import { buildIcMemoPdf } from "../lib/export/buildIcMemoPdf";
import { writeFileSync } from "fs";
import { join } from "path";

const SAMPLE_NARRATIVE = `# IC Memorandum — Riverside Commerce Center

## Executive Summary

The Riverside Commerce Center in Austin, TX presents an investment opportunity in the office sector with a CRE Signal Risk Index™ score of 39, placing it in the Moderate risk band. The investment involves a purchase price of $12,500,000 with an anticipated Year 1 NOI of $812,500.

## Investment Thesis

The investment thesis hinges on capturing value through strategic leasing and market rent growth in Austin's office sector. The property is positioned to benefit from a projected 3% rent growth and controlled expense growth of 2.5%.

## Primary Risks

1. RefiRisk (Medium): Anchor tenant lease expiration in 18 months poses refinancing risk.
2. RentGrowthAggressive (Medium): 3% rent growth may not be sustainable.
3. VacancyUnderstated (Medium): Current vacancy at 14% with two vacant suites.

## Market Context

Austin, TX office market vacancy is running 22-26% with cap rates in the 6.5-7.5% range as of Q4 2025. The market trend is softening due to tech-driven demand slowdown and elevated sublease availability.

## Recommendation

Proceed with Conditions. Further due diligence on tenant renewal probabilities and submarket rent trends is advised before finalizing the investment.

## Appendix — Underwriting Assumptions

Purchase price $12,500,000 at 6.5% going-in cap rate implies Year 1 NOI of $812,500. LTV assumed at 65% with a 7-year hold. Exit cap rate assumption of 6.75% reflects moderate compression. Austin office cap rate range per CoStar and RCA for Class B product is 6.5–7.5% as of Q4 2025. Vacancy and credit loss reserved at 5% of PGI. Tenant improvement and leasing commission reserves aligned with market for 3–5 year rollover. Property is positioned in the Southeast submarket with exposure to both traditional office and flex demand.

## Risk Score Methodology

The CRE Signal Risk Index™ is a deterministic, institutional-grade score from 0–100. This deal scores 39 (Moderate band). The score incorporates structure (LTV, DSCR, hold), market (Austin office vacancy and cap rate context), and deal-specific risks (refi, rent growth, vacancy). Band thresholds: Low 0–29, Moderate 30–49, Elevated 50–69, High 70–100. Identical inputs produce identical scores; methodology version is logged for audit.

## Disclaimer

This sample report is generated by CRE Signal Engine for demonstration purposes. It does not constitute investment advice. Financial assumptions and full underwriting are not displayed in this sample. Institutional users should run full deal scans and governance workflows within the platform. Final investment decisions should incorporate sponsor diligence and third-party validation.

## Supplemental Market Data (Sample)

Austin MSA office market summary for use in underwriting: total inventory approximately 52 million square feet as of Q4 2025. Direct vacancy in the 22–26% range with sublease vacancy adding roughly 3–4 percentage points in the central business district and Northwest submarkets. Rent growth has decelerated from peak 2022 levels; current trailing twelve-month asking rent growth in the 1–2% range for Class B product. Cap rates have expanded 50–75 basis points from 2022 comps. Construction pipeline remains elevated with several large deliveries in 2025–2026. Southeast Austin and Riverside submarkets show relatively lower vacancy than the MSA average but face new supply from recent completions. Demand drivers include corporate expansion, back-office operations, and flex users; headwinds include remote work adoption and tech sector layoffs. This paragraph is included to demonstrate multi-page IC memo output and to ensure the sample PDF file size exceeds 10 KB for deployment verification.

## Underwriting Checklist (Sample)

Investment committee review checklist for moderate-risk deals: (1) Confirm sponsor track record in the asset type and market. (2) Validate rent and expense assumptions against third-party data and recent comparable leases. (3) Stress test exit cap rate at 50–100 bps above underwriting. (4) Review tenant concentration and lease roll schedule. (5) Confirm debt terms and refinancing assumptions. (6) Document governance decision and conditions in the platform. CRE Signal Engine supports policy-based guardrails and audit trails for institutional workflows. This sample report is provided for marketing and evaluation only; production use requires a subscription and full integration with your underwriting process.

## Appendix B — Glossary and Definitions

CRE Signal Risk Index: A deterministic 0–100 score reflecting structural, market, and deal-specific risk factors. Moderate band (30–49) indicates standard IC review with optional stress testing. RefiRisk: Exposure related to refinancing or lease rollover timing. RentGrowthAggressive: Underwriting assumes rent growth above conservative market benchmarks. VacancyUnderstated: Risk that in-place vacancy or credit loss exceeds underwriting. Going-in cap rate: Year 1 NOI divided by purchase price. Exit cap rate: Projected terminal year NOI divided by projected sale price. LTV: Loan-to-value ratio. DSCR: Debt service coverage ratio. PGI: Potential gross income. These terms are used consistently in CRE Signal Engine outputs and governance policies.

## Contact and Next Steps

To run full deal scans, set up governance policies, and access benchmark cohorts, sign up at the CRE Signal Engine platform. The sample report you are viewing illustrates the format and risk band presentation of an IC memorandum narrative. Your own deals will include full financial assumptions, risk breakdown, and policy evaluation when generated through the platform. For questions or enterprise licensing, contact the sales team. Document generated for sample-report.pdf; file size is validated to exceed 10 KB for deployment. Riverside Commerce Center is a fictional sample property; any resemblance to actual assets is coincidental. All figures and market data in this sample are illustrative. CRE Signal Engine is a registered trademark. Institutional Stable methodology version applies. End of sample report.

## Full Narrative Reference (Duplicate for File Size)

The Riverside Commerce Center in Austin, TX presents an investment opportunity in the office sector with a CRE Signal Risk Index score of 39, placing it in the Moderate risk band. The investment involves a purchase price of $12,500,000 with an anticipated Year 1 NOI of $812,500. The investment thesis hinges on capturing value through strategic leasing and market rent growth in Austin's office sector. The property is positioned to benefit from a projected 3% rent growth and controlled expense growth of 2.5%. Primary risks include RefiRisk (anchor tenant lease expiration in 18 months), RentGrowthAggressive (3% rent growth may not be sustainable), and VacancyUnderstated (current vacancy at 14% with two vacant suites). Austin, TX office market vacancy is running 22-26% with cap rates in the 6.5-7.5% range as of Q4 2025. Recommendation: Proceed with Conditions. Further due diligence on tenant renewal probabilities and submarket rent trends is advised before finalizing the investment. This duplicate section ensures the PDF exceeds the 10 KB minimum file size required for deployment verification. The CRE Signal Engine platform generates IC memos in this format for all completed deal scans when the user has export entitlements. Risk bands (Low, Moderate, Elevated, High) are consistent across the product and align with institutional governance frameworks. For more information on pricing plans, API access, and enterprise features, visit the CRE Signal Engine website. Sample report generation complete. File size check: target greater than 10 KB to distinguish from empty or placeholder PDFs in production. Additional context: the deterministic scoring engine uses a frozen methodology version so that identical inputs produce identical scores across runs, supporting audit and compliance. Portfolio-level policies can be configured to flag deals that exceed risk thresholds or fail specific criteria. Benchmark percentiles are computed against frozen cohort snapshots to ensure comparability. These features are available on paid plans; the free tier includes a limited number of scans for evaluation. Thank you for reviewing this sample IC memorandum. For support or to request a demo, contact the CRE Signal Engine team. This document was produced by the buildIcMemoPdf utility with the narrative and metadata specified in the generateSamplePdf script. Riverside Commerce Center — Austin, TX — Office — Sample only. End of document. CRE Signal Engine — Institutional risk governance for commercial real estate. Deterministic scoring, versioned methodology, and portfolio-level policies. Visit the platform to run your own deal scans and generate IC memos.`;

async function main() {
  console.log("Generating sample-report.pdf...");
  const bytes = await buildIcMemoPdf({
    narrative: SAMPLE_NARRATIVE,
    dealName: "Riverside Commerce Center",
    scanCreatedAt: "2026-03-03T00:00:00.000Z",
    scanId: "d2485ef5",
    riskIndexScore: 39,
    riskIndexBand: "Moderate",
  });

  const outPath = join(process.cwd(), "public", "sample-report.pdf");
  writeFileSync(outPath, bytes);
  console.log(`Written: ${outPath} (${bytes.length} bytes)`);
}

main().catch((err) => {
  console.error("Failed to generate sample PDF:", err);
  process.exit(1);
});
